apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
# some metadata about the template itself
metadata:
  name: try-vnp-samp-template
  title: Test template by VNP
  description: Test template for learning
spec:
  owner: default
  type: service
  
  parameters:
    - title: Provide Repository Info
      required:
        - repoUrl
      properties:
        repoUrl:
          title: GitHub Repository URL
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            requestUserCredentials:
              secretsKey: USER_OAUTH_TOKEN
            allowedHosts:
              - github.com
              
    - title: Enter Personal data
      properties:
        name:
          title: Name
          type: string
          description: Enter your name
        age:
          title: Age
          type: integer
          description: Enter your age
          
  steps:
    - id: fetch-template
      name: Fetch Template file
      action: fetch:template
      input:
        url: ./skeleton
        targetpath: ./repo
        values: 
          name: ${{ parameters.name }}
          age: ${{ parameters.age }}
          repoName: ${{ (parameters.repoUrl | parseRepoUrl)['repo'] }}
          
    - id: publish-to-git
      name: Publish to Git
      action: publish:github:pull-request
      input:
        repoUrl: ${{ parameters.repoUrl }}
        branchName: add-hello-world
        title: 'Add HelloWorld.txt'
        description: |
          PR includes:
          - HelloWorld.txt with your input details
        sourcePath: ./repo
        token: ${{ secrets.USER_OAUTH_TOKEN }}
