apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: vnp-template-hello-world
  title: Hello World Demo by VNP
  description: VNP ---- Adds a HelloWorld.txt file to an existing github repo
spec:
  owner: default
  type: service
  
  parameters:
    - title: Provide Existing Repository Information
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository URL
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            requestUserCredentials:
              secretsKey: USER_OAUTH_TOKEN
            allowedHosts:
              - github.com
        
    - title: HelloWorld Details
      properties:
        projectName:
          title: Project Name
          type: string
          description: Name of the project
        description:
          title: Description
          type: string
          description: Project description

  steps:
    - id: fetch-template
      name: Fetch Documentation Template
      action: fetch:template
      input:
        url: ./skeleton
        targetPath: ./repo
        values:
          projectName: ${{ parameters.projectName }}
          description: ${{ parameters.description }}
          repoName: ${{ (parameters.repoUrl | parseRepoUrl)['repo'] }}
    - id: create-pr
      name: Create Pull Request
      action: publish:github:pull-request
      input:
        repoUrl: ${{ parameters.repoUrl }}
        branchName: backstage-helloworld
        title: 'demo: Add HelloWorld.txt using a Backstage Template'
        description: |
          This PR adds:
          - HelloWorld.txt with content populated from template
        sourcePath: ./repo
        # here's where the secret can be used
        token: ${{ secrets.USER_OAUTH_TOKEN }}
