apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: vnp-template-hello-world
  title: Hello World Demo by VNP
  description: VNP ---- Adds a HelloWorld.txt file to an existing github repo
spec:
  owner: default
  type: service
  
  parameters:
    - title: Provide Repository Info
      required:
        - repoUrl
      properties:
        repoUrl:
          title: GitHub Repository URL
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            requestUserCredentials:
              secretsKey: USER_OAUTH_TOKEN
            allowedHosts:
              - github.com
        
    - title: HelloWorld Details
      properties:
        name:
          title: Project Name
          type: string
          description: Name of the project
        age:
          title: Description
          type: string
          description: Project description
    - title: HelloWorld1 Details
      properties:
        company:
          title: company Name
          type: string
          description: Name of the company
        desg:
          title: desg
          type: string
          description: Project desg

  steps:
    - id: fetch-template
      name: Fetch Documentation Template
      action: fetch:template
      input:
        url: ./skeleton
        targetPath: ./output
        values:
          name: ${{ parameters.name }}
          age: ${{ parameters.age }}
          company: ${{ parameters.company }}
          desg: ${{ parameters.desg }}
          
    - id: publish-to-git
      name: Create Pull Request
      action: publish:github:pull-request
      input:
        repoUrl: ${{ parameters.repoUrl }}
        branchName: backstage-helloworld
        title: 'demo: Add HelloWorld.txt using a Backstage Template'
        description: |
          This PR adds:
          - HelloWorld.txt with content populated from template
        sourcePath: ./output
        # here's where the secret can be used
        token: ${{ secrets.USER_OAUTH_TOKEN }}
